### ISSUE TITLE
[doc] 6.3.2.9  Configure Path to Container Images

### ISSUE THREAD

**Issue by sebastian-philipp** [SUSE/doc-ses#398] opened 2020-06-29 12:41 UTC
### Type of report
   - [x] bug
   - [ ] feature request

### Source Document
6.3.2.9  Configure Path to Container Images:

https://susedoc.github.io/doc-ses/master/html/ses-deployment/deploy-cephadm.html#deploy-cephadm-configure-imagepath

### Summary

We **must** not use the `:latest` tag, as it breaks the upgrade to future maintenance updates. Unfortunately, when omitting an explicit image tag, the `:latest` tag will be **implicitly** used.

Therefore, we have to provide an example using a image tag. Like

```
ceph-salt config /containers/images/ceph set registry.suse.com/ses/7/ceph/ceph:7.0
```

or something. In any case, we have to **avoid** the implicit `:latest`. 

### Notes
GitHub issue in ceph-salt: https://github.com/ceph/ceph-salt/issues/280

**Comment by asettle** [comment] 2020-06-30 15:52
@sebastian-philipp maybe I'm crazy or reading this after it was fixed, but there is no `:latest` tag?

**Comment by sebastian-philipp** [comment] 2020-07-02 11:07
If you run `ceph-salt config /containers/images/ceph set registry.suse.com/ses/7/ceph/ceph`, it will use the `:latest` tag **implicitly**.

**Comment by asettle** [comment] 2020-07-02 11:10
> If you run `ceph-salt config /containers/images/ceph set registry.suse.com/ses/7/ceph/ceph`, it will use the `:latest` tag **implicitly**.

I guess what I'm saying is: your bug reports that the example should remove it. There is no `:latest` tag in the example. Do you want a note that says not to use it? The request is unclear.

**Comment by asettle** [comment] 2020-07-09 11:06
@mweiss reported this in bugzilla. Closed as a duplicate of this issue. Tracking in one place :)

**Comment by asettle** [comment] 2020-09-07 10:06
https://github.com/ceph/ceph/pull/36432 merged this morning

**Closed** 2020-09-07 12:42 UTC
Labels: MUST HAVE, SES7, bug
