### ISSUE TITLE
[doc] 5.2  Deploy Salt

### ISSUE THREAD

**Issue by holgis** [SUSE/doc-ses#788] opened 2020-11-20 07:09 UTC
### Type of report
   - [X] bug
   - [ ] feature request

### Source Document
5.2  Deploy Salt:

https://documentation.suse.com/ses/7/single-html/ses-deployment/#deploy-salt

### Summary
(Similar as in issue 787 but for salt-minion)
The default entry in /etc/salt/minion is not
`#log_level_logfile: WARN`
but
`#log_level_logfile:`
and needs to be changed to (while this is the default value anyway):
`log_level_logfile: warning`

**Comment by tbazant** [comment] 2020-11-23 10:34
@smithfarm @holgis if we want `warning` there and it is the default at the same time, why document it at all?

**Comment by tbazant** [comment] 2020-11-23 10:40
looks like this is a duplicate of #787

**Closed by tbazant** 2020-11-23 10:40 UTC
Labels: SES7, question
