### ISSUE TITLE
How to use the different user to mount the cephfs ?

### ISSUE THREAD

**Issue by yule-sun** [SUSE/doc-ses#879] opened 2021-02-02 11:00 UTC
Excuse me, sir,
 I'm bothering you again. Recently I was testing the tenant isolation feature of cephfs. But when I use the ceph-dokan.exe -l x -u -g command, the mapping always fails. I check the command description. It is possible to use other accounts to map the cephfs directory. Is there a problem with my settings? How to check the gid of the newly added account? I can only check the auid through ceph auth export client.test. Looking forward to your reply and help, thank you very much.

**Link To Section**
Please provide a link to the section or chapter you are requesting this feature for.

**Summary**

**Basic Example**

**Motivation**
A clear and concise description of what your motivation for requesting this change is.

**Notes**

**Comment by tbazant** [comment] 2021-03-03 08:26
@ml8mr  Mike, this looks like ceph on windows issue, can you comment 
on that please?

**Comment by ml8mr** [comment] 2021-03-31 00:16
We do support mounting the filesystem using a given uid/gid. The issue is likely that the command invocation is wrong. For example, “-u” took an uid argument, e.g. -u 1000, same for the gid.

The latest ceph-dokan version no longer takes those CLI arguments. The uid/gid is set through ceph.conf options. For more information see:  https://docs.ceph.com/en/latest/install/windows-basic-config/ and https://docs.ceph.com/en/latest/cephfs/ceph-dokan/#usage.

Keep in mind that the ceph.conf credentials are unrelated to the actual Windows OS credentials. For example, when mounting cephfs using a certain uid/gid, those cephfs credentials will be used regardless of the Windows user that’s initiating subsequent operations (e.g. creating or reading files). It’s somehow similar to Samba’s “force user” option.

Please let us know if that resolves your issue, and I'll look into updating our docs. (There is an updated version of the Windows driver that will be coming out soon as well.)

**Comment by tbazant** [comment] 2021-04-15 11:47
> We do support mounting the filesystem using a given uid/gid. The issue is likely that the command invocation is wrong. For example, “-u” took an uid argument, e.g. -u 1000, same for the gid.
> 
> The latest ceph-dokan version no longer takes those CLI arguments. The uid/gid is set through ceph.conf options. For more information see: https://docs.ceph.com/en/latest/install/windows-basic-config/ and https://docs.ceph.com/en/latest/cephfs/ceph-dokan/#usage.
> 
> Keep in mind that the ceph.conf credentials are unrelated to the actual Windows OS credentials. For example, when mounting cephfs using a certain uid/gid, those cephfs credentials will be used regardless of the Windows user that’s initiating subsequent operations (e.g. creating or reading files). It’s somehow similar to Samba’s “force user” option.
> 
> Please let us know if that resolves your issue, and I'll look into updating our docs. (There is an updated version of the Windows driver that will be coming out soon as well.)

@ml8mr i founf `ceph-dokan` mentioned here https://susedoc.github.io/doc-ses/main/single-html/ses-windows/#windows-cephfs. can you please tell me what snippet to update with what change, or do a pull request yourself? thank you!

**Comment by ml8mr** [comment] 2021-04-16 00:37
@tbazant Please let me know if the above PR is sufficient.

**Comment by tbazant** [comment] 2021-04-22 07:38
Closed by https://github.com/SUSE/doc-ses/commit/1dfb637baea1c16094778aa662f9590ae984c0d0

**Closed by tbazant** 2021-04-22 07:38 UTC
Labels: feature request
