### ISSUE TITLE
[doc] 15.13.2.7  Update the Ceph Configuration File

### ISSUE THREAD

**Issue by Martin-Weiss** [SUSE/doc-ses#238] opened 2020-04-15 06:45 UTC
15.13.2.7  Update the Ceph Configuration File

https://documentation.suse.com/ses/6/single-html/ses-admin/#update-ceph-config-file

------
Could we add the exact files and adjustments required so that deepsea setup matches the ceph.conf adjustments required for this multi-zone RGW setup and where each RGW has the correct zone in the ceph.conf even after running through all deepsea stages?

(global.yml, rgw...conf,...)

**Comment by Martin-Weiss** [comment] 2020-04-15 06:46
As deepsea is used - the ceph.conf MUST NOT be modified manually locally to the RGW gateways as the next time the deepsea stages will be executed - the manual changed ceph.conf settings will be removed!

**Comment by asettle** [comment] 2020-04-15 09:20
@Martin-Weiss I will leave this until you and @swiftgist have agreed on a proposed step forward as requested in my email and notes in the BSC :) The confusion in BSC#1135872 rendered the bug incomprensible and I wish to avoid that again. I need to understand the following as your current bug report is not enough to go on:

1. Is this a bug or a feature request?
-  If this is a bug: Why is it a bug and what issues are customers/yourself presenting?
- If this is a feature request for docs: Outline the exact changes required and in what section you need to see this in
2. If this is a bug, fill out the following template: `Summary`, `Steps to Reproduce`, `Expected Results`, `Actual Results`, and any further supporting `Notes`
3. If this is a feature request, fill out the following template: `Summary`, `Basic example`, `Motivation`

**Comment by Martin-Weiss** [comment] 2020-04-15 12:33
> 
> 
> @Martin-Weiss I will leave this until you and @swiftgist have agreed on a proposed step forward as requested in my email and notes in the BSC :) The confusion in BSC#1135872 rendered the bug incomprensible and I wish to avoid that again. I need to understand the following as your current bug report is not enough to go on:
> 
>     1. Is this a bug or a feature request?
> 
> 
>     * If this is a bug: Why is it a bug and what issues are customers/yourself presenting?

IMO it is a bug because if you follow the changes in the chapter for setting up a multizone and replication for RGW following the examples and then re-run deepsea stages - the manual changes in the ceph.conf get removed by deepsea.

> 
>     * If this is a feature request for docs: Outline the exact changes required and in what section you need to see this in
> 
> 
>     1. If this is a bug, fill out the following template: `Summary`, `Steps to Reproduce`, `Expected Results`, `Actual Results`, and any further supporting `Notes`
> 

Summary: Could we add the exact files and adjustments required so that deepsea setup matches the ceph.conf adjustments required for this multi-zone RGW setup and where each RGW has the correct zone in the ceph.conf even after running through all deepsea stages?

Steps to reproduce: after following the documented guideline for setting up a multizone-rgw environment with manually modification of ceph. conf - re-run deepsea stages 0..5 and see the ceph.conf on the rgw nodes. They will not have the manual modifications anymore.

Expected Results: ceph.conf has the required settings for multizone setup / config  even after re-running deepsea stages

Actual Result: ceph.conf does not have the manual configured adjustments of ceph.conf on the RGW nodes anymore after re-running deepsea stages.


>     2. If this is a feature request, fill out the following template: `Summary`, `Basic example`, `Motivation`

**Comment by asettle** [comment] 2020-04-15 12:46
@Martin-Weiss - under no circumstance should you be applying _any_ updates to the ceph.conf because (as you say) the manually configured adjustments of the ceph.conf will be wiped after re-running DeepSea changes. This is because DeepSea does not support multiple zones or realms. 

As we have [recommended in the documentation](https://susedoc.github.io/doc-ses/ses6/single-html/ses-admin/#ds-custom-cephconf), you need to create an rgw.conf file to manually write these changes to. When you do this, you will be able to run DeepSea stages. See: https://susedoc.github.io/doc-ses/ses6/single-html/ses-admin/#update-ceph-config-file

If you have a suggestion on how to make this more clear, I would be interested to know. But what you are asking for is not something that is supported by DeepSea, and not something we can action in documentation. If you would like a feature request, it is best that this is redirected towards PM.

**Comment by Martin-Weiss** [comment] 2020-04-15 12:59
This is what needs to be changed.. especially the sentence "Update the Ceph configuration file on master zone hosts" in the following:
-------------------------------------------

15.13.2.7 Update the Ceph Configuration File

Update the Ceph configuration file on master zone hosts by adding the rgw_zone configuration option and the name of the master zone to the instance entry.

[client.rgw.INSTANCE-NAME]
...
rgw_zone=ZONE-NAME

For example:

[client.rgw.rgw1]
host = rgw1
rgw frontends = "beast port=80"
rgw_zone=us-east

-------------------------------------------

In this chapter we have to explain which rgw.conf files need to be created and what their content needs to be with the details of the multi-zone rgw setup example.. 
Best is thinking of having multiple zones in the same cluster and also multiple gateways for different zones in that cluster.

So add the config files that need to be created or adjusted in the deepsea structure as examples, here.

I.e. add ???? to /.../.../global.yaml
create file /.../.../rgw-primary-zone-us.conf with the following content:
<content>
create file /.../.../rgw-secondary-zone-emea.conf with the following content:
<content>
create file /.../.../rgw-primary-zone-emea.conf with the following content:
<content>

The details for "...", "????", "*.conf" is what I believe we should document in this chapter 15.13.2.7 but unfortunately I can not deliver them.

**Comment by swiftgist** [comment] 2020-04-15 15:56
Okay... based on reading the zone names from 15.13.2.3 and 15.13.3.2 which are `us-east-1` and `us-east-2` respectively, then I believe you want the example for 15.13.2.7 to be

```
[client.{{ client }}]
rgw frontends = "beast port={{ pillar.get('rgw_frontend_port', 80) }}"
rgw dns name = {{ fqdn }}
rgw enable usage log = true
rgw zone = {{ client }}
```
which is placed in /srv/salt/ceph/configuration/files/ceph.conf.d/us-east-1.conf.

Since you are not using the default rgw zone, then /srv/pillar/ceph/stack/global.yml contains
```
rgw_configurations:
  - us-east-1
```

For the second cluster example in 15.13.3.3, the configuration is similar for `us-east-2`

```
[client.{{ client }}]
rgw frontends = "beast port={{ pillar.get('rgw_frontend_port', 80) }}"
rgw dns name = {{ fqdn }}
rgw enable usage log = true
rgw zone = {{ client }}
```
which is placed in /srv/salt/ceph/configuration/files/ceph.conf.d/us-east-2.conf.

likewise, the /srv/pillar/ceph/stack/global.yml would contain

```
rgw_configurations:
  - us-east-2
```

---
Next questions: I used the default `rgw.conf` as a template here, but I don't know if that's desired.  Using the `{{ client }}` jinja evaluation is simply to prevent typos.  Also, I do not know if the `rgw dns name` and `rgw enable usage log` are necessary for a multi-site setup.  OTOH, I don't know what they would hurt.

@Martin-Weiss Is the above effectively what you were after? ... in other words the examples in those specific sections didn't reflect the names used in the prior sections.

**Comment by asettle** [comment] 2020-10-09 14:33
Closing, issue has been untouched since April 2020. Reopen if there is something to happen here.

**Closed by asettle** 2020-10-09 14:33 UTC
