### ISSUE TITLE
[doc] 2.1  Network Overview

### ISSUE THREAD

**Issue by denisok** [SUSE/doc-ses#495] opened 2020-08-27 13:26 UTC
### Type of report
   - [ ] bug
   - [x] feature request

### Source Document
2.1  Network Overview:

https://susedoc.github.io/doc-ses/master/single-html/ses-deployment/#network-overview

### Summary
`ceph orch` should be used instead of systemctl and way how to configure cluster_network with `ceph orch` should be defined.

### Steps To Reproduce
document is just not applicable with `ceph orch`

### Expected Results
clear definition for `ceph orch`

### Actual Results
old documentation for systemd based deployments.

### Notes
https://jira.suse.com/browse/SES-2134

**Comment by asettle** [comment] 2020-08-27 13:49
Having spoken to @sebastian-philipp about this, he recommends using `systemctl stop ceph.target`. Using `ceph orc daemon stop...` will require the user to do it for each individual daemon, whereas `systemctl` applies a complete stop.

**Comment by asettle** [comment] 2020-08-27 14:30
Regarding "Add a line to /etc/ceph/ceph.conf to define the cluster network, for example:" - I have spoken to Denis Polom, and he said the cluster network should look like the following: 

`ceph config set osd cluster_network 10.0.0.0/24`
and public:
`ceph config set mon public_network 10.8.0.0/24`

**Comment by denisok** [comment] 2020-08-27 14:39
> Regarding "Add a line to /etc/ceph/ceph.conf to define the cluster network, for example:" - I have spoken to Denis Polom, and he said the cluster network should look like the following:
> 
> `ceph config set osd cluster_network 10.0.0.0/24`

in theory, but I think it didn't work for him. I think cluster_network could be changed only in `ceph.conf`. If @dthpulse confirms I am fine.

**Comment by dthpulse** [comment] 2020-08-27 17:55
I can confirm. These parameters are ignored if they are set by `ceph config set` command. If they are specified in `/etc/ceph/ceph.conf` then they are recognized by Ceph cluster. 
Tested simply with `iftop` during some load on the cluster.
Just thinking if it is bug or expected behavior as these parameters are listed under both:
`ceph config ls`
and
`ceph-conf -D`
The last one is giving the right output only if parameters are specified in `/etc/ceph/ceph.conf` file.

**Comment by asettle** [comment] 2020-08-28 11:06
> I can confirm. These parameters are ignored if they are set by `ceph config set` command. If they are specified in `/etc/ceph/ceph.conf` then they are recognized by Ceph cluster.
> Tested simply with `iftop` during some load on the cluster.
> Just thinking if it is bug or expected behavior as these parameters are listed under both:
> `ceph config ls`
> and
> `ceph-conf -D`
> The last one is giving the right output only if parameters are specified in `/etc/ceph/ceph.conf` file.

Okay, so, what is currently in the documentation is correct and remain as such.

**Comment by denisok** [comment] 2020-08-28 14:08
So:
`Add a line to /etc/ceph/ceph.conf to define the cluster network, for example: ` is definitely incorrect because there is no such file.


I tried `systemctl stop ceph\*.service ceph\*.target`, it took sometime but looks like stopped it.

But `systemctl start ceph.target` didn't bring it up. So looks like it doesn't work.

What I did:
```
sesdev create octopus --single-node mini
```

ssh to machine and executed the doc. Services stopped but ``systemctl start ceph.target` didn't bring it up.

**Comment by asettle** [comment] 2020-08-28 14:15
@denisok @dthpulse - so, this doesn't leave me with much:

1. The `ceph config set` command doesn't work because the parameters will be ignored, but I can't use `ceph.conf` as it no longer exists. 
2. We will keep `systemctl stop` but the result means that you have to redeploy? Unfortunately, sesdev doesn't give me a lot to work with there.

I need to know where we now define the cluster network (maybe we create a file? cluster_network.yaml?) and how we regain access to a stopped cluster. @sebastian-philipp any thoughts?

**Comment by denisok** [comment] 2020-08-28 14:18
@asettle , @sebastian-philipp  needs to answer that, or find ppl to answer.

**Comment by asettle** [comment] 2020-08-28 14:30
The problem is right now that "cluster_network" cannot be set by the "ceph config set" command without being overriden by the ceph.conf. And you can't set the variable in a global "ceph.conf" file, you would have to set it for each individual daemon. There are also other cases when the parameters needs to be propagated to the Ceph services via "ceph.conf".

Working with @sebastian-philipp

**Comment by dthpulse** [comment] 2020-08-28 14:42
I would say it is definitely a bug. According https://ceph.readthedocs.io/en/latest/rados/configuration/ceph-conf/#commands
and using `ceph config assimilate-conf -i <input file> -o <output file>` it works and was added to configuration. I assume that if it would be invalid or ignored option ie will be putted to output file as documentation says.

**Comment by sebastian-philipp** [comment] 2020-08-28 15:05
https://github.com/ceph/ceph/pull/36884

**Comment by sebastian-philipp** [comment] 2020-08-28 15:17
ok let's reopen this for #498

**Comment by asettle** [comment] 2020-08-28 15:18
> ok let's reopen this for #498

This can stay closed, it only fixes two other issues.

**Comment by denisok** [comment] 2020-08-28 15:31
sorry, but what about `systemctl` changes, where is that tracked ? and how to change `ceph.cofnf` file ?
That still needs to be updated for the cluster that were deployed and needs changes in networking later.

**Comment by asettle** [comment] 2020-08-28 15:38
@denisok we cannot track changes to `systemctl` here - at the moment, I've got nothing to add to the docs. The command works, we just need to know how to pull the cluster back up once it's been stopped, but that needs to be discussed. 

Until https://github.com/ceph/ceph/pull/36884 is merged, we can't make any updates regarding the `ceph.conf` file either. We can create a new issue when it's finalised.

**Comment by denisok** [comment] 2020-08-28 15:44
@sebastian-philipp please clarify doc update for the `systemctl`, also changes to `ceph.conf` how to do that.

**Comment by jecluis** [comment] 2020-08-31 12:01
I'm unsure what the expectation is, but I've tested this on blueshark and it works as I expected: setting `ceph config osd cluster_network <my_network>` and restarting the osds will have the osds binding to the specified cluster network. I have the general feeling that some might be expecting this operation to be magical without needing a daemon restart?

**Comment by denisok** [comment] 2020-08-31 12:11
and restart should be performed with `systemctl restart ceph-*@osd.*.service` instead of stop and start.

**Comment by denisok** [comment] 2020-08-31 12:44
@asettle so, instead of `ceph.conf`: `ceph config osd cluster_network <my_network>`

don't need to stop, just after the change - restart OSD demons om all nodes, on each node: `systemctl restart ceph-*@osd.*.service`

**Closed** 2020-09-01 14:12 UTC
Labels: MUST HAVE, SES7, bug
